# Grafana Datasources Configuration

apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "15s"
    version: 1

  - name: PostgreSQL-DWH
    type: postgres
    access: proxy
    url: postgres:5432
    database: energy_dwh
    user: energy_user
    secureJsonData:
      password: energy_password
    jsonData:
      sslmode: "disable"
      maxOpenConns: 10
      maxIdleConns: 10
      connMaxLifetime: 14400
    editable: true
    version: 1